name: deploy notes.hasanjoldic.com

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            if cd /root/apps/notes.hasanjoldic.com; then git pull; 
            else git clone git@github.com:hasanjoldic/notes.hasanjoldic.com.git /root/apps/notes.hasanjoldic.com; 
            fi
            echo "" >> .npmrc
            echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> .npmrc
            git update-index --assume-unchanged .npmrc
            cat .npmrc
            cd /root/apps/notes.hasanjoldic.com && docker-compose up --build --detach
          host: notes.hasanjoldic.com
          username: root
          privateKey: ${{ secrets.HASAN_JOLDIC_COM_PRIVATE_KEY }}
